Include missing "fstream" header file
This change fixes compilation errors:

    fileutils.cpp: In function ‘std::vector<char> read_file(boost::filesystem::path)’:
    fileutils.cpp:74:21: error: variable ‘std::ifstream ifs’ has initializer but incomplete type

    fileutils.cpp: In function ‘void write_file(boost::filesystem::path, const std::vector<char>&)’:
    fileutils.cpp:87:21: error: variable ‘std::ofstream ofs’ has initializer but incomplete type